### ISSUE TITLE
Error loading sytstem settings page on reduced privilege accounts

### ISSUE THREAD

**Issue by jacobsen9026** [Blazam-App/BLAZAM#229]
Error Message: Access to the registry key 'Global' is denied.
Stack Trace:
at System.Diagnostics.PerformanceDataRegistryKey.Win32Error(Int32& errorCode, String name)

at System.Diagnostics.PerformanceDataRegistryKey.GetValue(String name, Boolean usePool)

at System.Diagnostics.PerformanceMonitor.GetData(String item, Boolean usePool)

at System.Diagnostics.PerformanceCounterLib.GetPerformanceData(String item, Boolean usePool)

at System.Diagnostics.PerformanceCounterLib.get_CategoryTable()

at System.Diagnostics.PerformanceCounterLib.CounterExists(String category, String counter, Boolean& categoryExists)

at System.Diagnostics.PerformanceCounterLib.CounterExists(String machine, String category, String counter)

at System.Diagnostics.PerformanceCounter.InitializeImpl()

at System.Diagnostics.PerformanceCounter.Initialize()

at System.Diagnostics.PerformanceCounter..ctor(String categoryName, String counterName, String instanceName, Boolean readOnly)

at System.Diagnostics.PerformanceCounter..ctor(String categoryName, String counterName, String instanceName)

at BLAZAM.Gui.UI.Settings.ProcessResourceUsage.b__12_1() in D:\a\BLAZAM\BLAZAM\BLAZAMGui\UI\Settings\ProcessResourceUsage.razor:line 61

at System.Threading.Tasks.Task.InnerInvoke()

at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)

--- End of stack trace from previous location ---

at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)

--- End of stack trace from previous location ---

at BLAZAM.Gui.UI.Settings.ProcessResourceUsage.OnInitializedAsync() in D:\a\BLAZAM\BLAZAM\BLAZAMGui\UI\Settings\ProcessResourceUsage.razor:line 59

at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()

at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)

**Comment by jacobsen9026** [comment]
Fixed
