### ISSUE TITLE
System settings page dependency injection disposal issue

### ISSUE THREAD

**Issue by jacobsen9026** [Blazam-App/BLAZAM#235]
Error Message: Cannot access a disposed context instance. A common cause of this error is disposing a context instance that was resolved from dependency injection and then later trying to use the same context instance elsewhere in your application. This may occur if you are calling 'Dispose' on the context instance, or wrapping it in a using statement. If you are using dependency injection, you should let the dependency injection container take care of disposing context instances. Object name: 'SqlDatabaseContext'.
Stack Trace:
at Microsoft.EntityFrameworkCore.DbContext.CheckDisposed()

at Microsoft.EntityFrameworkCore.DbContext.get_ContextServices()

at Microsoft.EntityFrameworkCore.DbContext.get_ChangeTracker()

at Microsoft.EntityFrameworkCore.Query.CompiledQueryCacheKeyGenerator.GenerateCacheKeyCore(Expression query, Boolean async)

at Microsoft.EntityFrameworkCore.Query.RelationalCompiledQueryCacheKeyGenerator.GenerateCacheKeyCore(Expression query, Boolean async)

at Microsoft.EntityFrameworkCore.SqlServer.Query.Internal.SqlServerCompiledQueryCacheKeyGenerator.GenerateCacheKey(Expression query, Boolean async)

at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)

at BLAZAM.Gui.UI.Settings.SystemSettings.OnInitializedAsync() in D:\a\BLAZAM\BLAZAM\BLAZAMGui\UI\Settings\SystemSettings.razor:line 53

at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()

at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)

**Comment by jacobsen9026** [comment]
Fixed
