### ISSUE TITLE
After moving user

### ISSUE THREAD

**Issue by jacobsen9026** [Blazam-App/BLAZAM#236]
BLAZAM : System.NullReferenceException
Error Message: Object reference not set to an instance of an object.
Stack Trace:
at BLAZAM.Pages.OU.ViewOU.OnInitializedAsync() in D:\a\BLAZAM\BLAZAM\BLAZAM\Pages\OU\ViewOU.razor:line 78

at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()

at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)

**Comment by jacobsen9026** [comment]
Unsure of the source of this, as it's a user. Doesn't happen in dev env

**Comment by jacobsen9026** [comment]
Fix for error nonetheless
