### ISSUE TITLE
BLAZAMSession : System.NullReferenceException" Stack Trace: at BLAZAM.Session.ApplicationNewsService.

### ISSUE THREAD

**Issue by swamipurnamsha** [Blazam-App/BLAZAM#289]
Hi @jacobsen9026 

I see that the error output shows that some part of this code is fixed however, a new error output is being thrown for the same ApplicationNewsService.cs, image attached:

Something terrible has happened...
BLAZAMSession : System.NullReferenceException
Error Message: Object reference not set to an instance of an object.
Stack Trace:
at BLAZAM.Session.ApplicationNewsService.GetUnreadNewsItems(IApplicationUserState user) in D:\a\BLAZAM\BLAZAM\BLAZAMSession\ApplicationNewsService.cs:line 69

at BLAZAM.Gui.UI.Outputs.ApplicationNewsProvider.RefreshUnreadItems() in D:\a\BLAZAM\BLAZAM\BLAZAMGui\UI\Outputs\ApplicationNewsProvider.razor:line 111

at BLAZAM.Gui.UI.Outputs.ApplicationNewsProvider.RefreshItems() in D:\a\BLAZAM\BLAZAM\BLAZAMGui\UI\Outputs\ApplicationNewsProvider.razor:line 96

at BLAZAM.Gui.UI.Outputs.ApplicationNewsProvider.OnInitialized() in D:\a\BLAZAM\BLAZAM\BLAZAMGui\UI\Outputs\ApplicationNewsProvider.razor:line 92

at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()

![image](https://github.com/Blazam-App/BLAZAM/assets/164919767/ce7d0c47-3087-45ea-834d-45a67109ecf5)

_Originally posted by @swamipurnamsha in https://github.com/Blazam-App/BLAZAM/issues/276#issuecomment-2033685432_

**Comment by jacobsen9026** [comment]
Yup that one came up in my dev branch, already squashed. Just need to get it through the vetting phase and up to Stable branch for ya. Not sure when, but probably sometime between Thursday and Saturday.

Is there any filtering or lack of an internet connection to the server running Blazam? The error doesn't occur unless it can't reach the news server on the internet. Which it absolutely should be able to handle and is not an excuse, but would help in solidifying my theory on the cause.

**Comment by swamipurnamsha** [comment]
@jacobsen9026

Yes, the server has internet connectivity. 

We moved on to running the Blazam App as a service instead of through IIS, for which there are separate issues. I will raise the witnessed issues in a separate issue thread.

**Comment by jacobsen9026** [comment]
Thanks for the info, I will focus on stabilizing the new news system in the next update.

**Comment by jacobsen9026** [comment]
Stabilized news operations. Commit ID: 8d0f4bfa15bf992482d7b04f1058b988f574ae9a
