### ISSUE TITLE
Another possible memory leak in live computer monitoring

### ISSUE THREAD

**Issue by jacobsen9026** [Blazam-App/BLAZAM#329]
Error
{Data: [], HResult: -2146232832, HelpLink: null, InnerException: null, Message: 'Impersonation running as application identity', Source: null, StackTrace: '   at BLAZAM.Common.Data.WindowsImpersonation.<>c__DisplayClass18_0`1.<Run>b__0() in D:\a\BLAZAM\BLAZAM\BLAZAMCommon\Data\WindowsImpersonation.cs:line 107
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Security.Principal.WindowsIdentity.RunImpersonatedInternal(SafeAccessTokenHandle token, Action action)
   at BLAZAM.Common.Data.WindowsImpersonation.Run[T](Func`1 task) in D:\a\BLAZAM\BLAZAM\BLAZAMCommon\Data\WindowsImpersonation.cs:line 99
   at BLAZAM.ActiveDirectory.Adapters.RemoteSession.GetNewSessionState() in D:\a\BLAZAM\BLAZAM\BLAZAMActiveDirectory\Adapters\RemoteSession.cs:line 236
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
   at System.Threading.TimerQueue.FireNextTimers()
   at System.Threading.UnmanagedThreadPoolWorkItem.ExecuteUnmanagedThreadPoolWorkItem(IntPtr callback, IntPtr state)
   at System.Threading.UnmanagedThreadPoolWorkItem.ExecuteUnmanagedThreadPoolWorkItem(IntPtr callback, IntPtr state)
   at System.Threading.UnmanagedThreadPoolWorkItem.System.Threading.IThreadPoolWorkItem.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
--- End of stack trace from previous location ---

**Comment by jacobsen9026** [comment]
Error
{Data: [], ErrorCode: -2147467259, HResult: -2147467259, HelpLink: null, InnerException: null, Message: 'The system cannot find the file specified.', NativeErrorCode: 2, Source: 'Cassia', StackTrace: '   at Cassia.Impl.NativeMethodsHelper.QuerySessionInformation[T](ITerminalServerHandle server, Int32 sessionId, WTS_INFO_CLASS infoClass, ProcessSessionCallback`1 callback)
   at Cassia.Impl.NativeMethodsHelper.QuerySessionInformationForString(ITerminalServerHandle server, Int32 sessionId, WTS_INFO_CLASS infoClass)
   at Cassia.Impl.TerminalServicesSession..ctor(ITerminalServer server, Int32 sessionId)
   at Cassia.Impl.TerminalServer.GetSession(Int32 sessionId)
   at BLAZAM.ActiveDirectory.Adapters.RemoteSession.<GetNewSessionState>b__48_0() in D:\a\BLAZAM\BLAZAM\BLAZAMActiveDirectory\Adapters\RemoteSession.cs:line 250
   at BLAZAM.Common.Data.WindowsImpersonation.<>c__DisplayClass18_0`1.<Run>b__0() in D:\a\BLAZAM\BLAZAM\BLAZAMCommon\Data\WindowsImpersonation.cs:line 104
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Security.Principal.WindowsIdentity.RunImpersonatedInternal(SafeAccessTokenHandle token, Action action)
   at BLAZAM.Common.Data.WindowsImpersonation.Run[T](Func`1 task) in D:\a\BLAZAM\BLAZAM\BLAZAMCommon\Data\WindowsImpersonation.cs:line 132', TargetSite: 'T QuerySessionInformation[T](Cassia.ITerminalServerHandle, Int32, Cassia.Impl.WTS_INFO_CLASS, ProcessSessionCallback`1)'}
